### ISSUE TITLE
Missing 44 Hadiths in Bukhari

### ISSUE THREAD

**Issue by Nusab19** [sunnah-com/website#106]
Assalamu Alaikum Wa Rahmatullah.

I tried to find the following hadiths in sunnah.com in **_Bukhari_**.
`1687, 1695, 2360, 2384, 2417, 2516, 2556, 2584, 2608, 2667, 2670, 2677, 2696, 2725, 2789, 2800, 2878, 2895, 3187, 3723, 3741, 4454, 5709, 5710, 5711, 5712, 5773, 5774, 5775, 6073, 6074, 6075, 6089, 6090, 6173, 6174, 6175, 6826, 6940, 7268, 7269, 7270, 7271, 7272`

But it wasn't there. These **_44_** hadiths are missing from Bukhari. I don't know the reason. Is it a bug or intentional?

One of them's url: https://sunnah.com/bukhari:1687

**Comment by mha6** [comment]
In all of these cases, the next hadith is included in combination with the previous one. For example, with the first example, the unit numbered 1687 is the part that begins with ""
