### ISSUE TITLE
Copy Hadith feature with selectable options

### ISSUE THREAD

**Issue by fsid** [sunnah-com/website#71]
Add a new permalink, **Copy**, that copies the Hadith to the clipboard.

### Default format:
```
{Arabic Text}

{Translated Text}

{Collection name} {Hadith number}
{Hadith link}
```

Also add a caret next to the link that opens a flyout with options. Save options on change, locally.

### Options in the flyout:

- Arabic
- Translation (Selected language)
- Reference Arabic
- Reference English
- Detailed Reference (Adds book and chapter details)
- Do not add a link

### Notes:
- Use the colon link
- Make visually known that the hadith was copied. Perhaps a quick fading text _Copied_ above the link
- Final format: TBD
- Keep discussion here incremental and brief

**Comment by naushervan** [comment]
I have implemented it, alḥamdulillāh!

**Comment by ahadith** [comment]
Ma sha Allah @naushervan! Can you submit a pull request with your changes and include screenshots and such to illustrate the change?
