### ISSUE TITLE
Copy function not working on search results page

### ISSUE THREAD

**Issue by ahadith** [sunnah-com/website#87]
In the search results, the entire result is linked to the hadith page, so when a user clicks on copy, it takes them to the hadith page instead of copying to clipboard.

**Comment by fsid** [comment]
I do not think it is necessary to show the copy button on the search page.

For longer ahadith, we also show excerpts with a "Read more" for the Arabic text. If we are to allow the copy feature on the Search pages, we'd have to include full text.

I think we can remove it like all the other utility options in hadith_permalink element. It also keeps the Search page more focused.

**Comment by ahadith** [comment]
Agreed. Let's remove the copy button from the search results page. @naushervan can you take this?

**Comment by naushervan** [comment]
@ahadith  Will do (in-shāʾAllāh).

> Agreed. Let's remove the copy button from the search results page. @naushervan can you take this?
