### ISSUE TITLE
Copy hadith to clipboard doesn't work in firefox

### ISSUE THREAD

**Issue by fawazahmed0** [sunnah-com/website#98]
clicking copy button doesn't copy anything in firefox, but works fine in chrome

![Screenshot (505)](https://user-images.githubusercontent.com/20347013/155860428-6aa8e2b4-3c1c-4966-b57b-347259b9fdc3.png)

**Firefox console error:**
```
Uncaught (in promise) TypeError: 'clipboard-write' (value of 'name' member of PermissionDescriptor) is not a valid value for enumeration PermissionName.
    cbCopy https://sunnah.com/js/sunnah.js?ver=1618072554:243
    jQuery 8
    <anonymous> https://sunnah.com/js/sunnah.js?ver=1618072554:545
    jQuery 13
sunnah.js:243:26

```

**Comment by ahadith** [comment]
Jazakumullahu khair - I've deployed this to the server.
